package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ProcurementApp implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<com.myspace.ghtprocurementprocess.ItemAudit> itemAudit;
	private java.util.List<com.myspace.ghtprocurementprocess.ItemInformation> itemInformation;
	@org.kie.api.definition.type.Label("ItmReqObj")
	private com.myspace.ghtprocurementprocess.ItmReqObj itmReqObj;

	public ProcurementApp() {
	}

	public java.util.List<com.myspace.ghtprocurementprocess.ItemAudit> getItemAudit() {
		return this.itemAudit;
	}

	public void setItemAudit(
			java.util.List<com.myspace.ghtprocurementprocess.ItemAudit> itemAudit) {
		this.itemAudit = itemAudit;
	}

	public java.util.List<com.myspace.ghtprocurementprocess.ItemInformation> getItemInformation() {
		return this.itemInformation;
	}

	public void setItemInformation(
			java.util.List<com.myspace.ghtprocurementprocess.ItemInformation> itemInformation) {
		this.itemInformation = itemInformation;
	}

	public com.myspace.ghtprocurementprocess.ItmReqObj getItmReqObj() {
		return this.itmReqObj;
	}

	public void setItmReqObj(
			com.myspace.ghtprocurementprocess.ItmReqObj itmReqObj) {
		this.itmReqObj = itmReqObj;
	}

	public ProcurementApp(
			java.util.List<com.myspace.ghtprocurementprocess.ItemAudit> itemAudit,
			java.util.List<com.myspace.ghtprocurementprocess.ItemInformation> itemInformation,
			com.myspace.ghtprocurementprocess.ItmReqObj itmReqObj) {
		this.itemAudit = itemAudit;
		this.itemInformation = itemInformation;
		this.itmReqObj = itmReqObj;
	}

}